apiVersion: v1
kind: Service
metadata:
  name: eks-production-service
  namespace: production

spec:
  type: LoadBalancer

  selector:
    app: eks-production-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
